// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: ai/v1/ai.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	OwnerId string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Query   string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	// name | fulltext | semantic | hybrid
	Mode              string   `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	FolderId          *string  `protobuf:"bytes,4,opt,name=folder_id,json=folderId,proto3,oneof" json:"folder_id,omitempty"`
	IncludeSubfolders bool     `protobuf:"varint,5,opt,name=include_subfolders,json=includeSubfolders,proto3" json:"include_subfolders,omitempty"`
	MimeTypes         []string `protobuf:"bytes,6,rep,name=mime_types,json=mimeTypes,proto3" json:"mime_types,omitempty"`
	Limit             int32    `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_ai_v1_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *SearchRequest) GetFolderId() string {
	if x != nil && x.FolderId != nil {
		return *x.FolderId
	}
	return ""
}

func (x *SearchRequest) GetIncludeSubfolders() bool {
	if x != nil {
		return x.IncludeSubfolders
	}
	return false
}

func (x *SearchRequest) GetMimeTypes() []string {
	if x != nil {
		return x.MimeTypes
	}
	return nil
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type FileRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	FolderId      string                 `protobuf:"bytes,3,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	ObjectId      string                 `protobuf:"bytes,4,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,6,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	MimeType      string                 `protobuf:"bytes,7,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Version       int64                  `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRef) Reset() {
	*x = FileRef{}
	mi := &file_ai_v1_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRef) ProtoMessage() {}

func (x *FileRef) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRef.ProtoReflect.Descriptor instead.
func (*FileRef) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{1}
}

func (x *FileRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileRef) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *FileRef) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *FileRef) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *FileRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileRef) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FileRef) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileRef) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *FileRef) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *FileRef) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Citation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	PageNumber    *int32                 `protobuf:"varint,4,opt,name=page_number,json=pageNumber,proto3,oneof" json:"page_number,omitempty"`
	Section       *string                `protobuf:"bytes,5,opt,name=section,proto3,oneof" json:"section,omitempty"`
	Excerpt       string                 `protobuf:"bytes,6,opt,name=excerpt,proto3" json:"excerpt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Citation) Reset() {
	*x = Citation{}
	mi := &file_ai_v1_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Citation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Citation) ProtoMessage() {}

func (x *Citation) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Citation.ProtoReflect.Descriptor instead.
func (*Citation) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{2}
}

func (x *Citation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Citation) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *Citation) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Citation) GetPageNumber() int32 {
	if x != nil && x.PageNumber != nil {
		return *x.PageNumber
	}
	return 0
}

func (x *Citation) GetSection() string {
	if x != nil && x.Section != nil {
		return *x.Section
	}
	return ""
}

func (x *Citation) GetExcerpt() string {
	if x != nil {
		return x.Excerpt
	}
	return ""
}

type SearchHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileRef               `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	MatchType     string                 `protobuf:"bytes,3,opt,name=match_type,json=matchType,proto3" json:"match_type,omitempty"`
	Citations     []*Citation            `protobuf:"bytes,4,rep,name=citations,proto3" json:"citations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHit) Reset() {
	*x = SearchHit{}
	mi := &file_ai_v1_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHit) ProtoMessage() {}

func (x *SearchHit) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHit.ProtoReflect.Descriptor instead.
func (*SearchHit) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{3}
}

func (x *SearchHit) GetFile() *FileRef {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *SearchHit) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchHit) GetMatchType() string {
	if x != nil {
		return x.MatchType
	}
	return ""
}

func (x *SearchHit) GetCitations() []*Citation {
	if x != nil {
		return x.Citations
	}
	return nil
}

type AskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Question      string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	FolderId      *string                `protobuf:"bytes,3,opt,name=folder_id,json=folderId,proto3,oneof" json:"folder_id,omitempty"`
	FileIds       []string               `protobuf:"bytes,4,rep,name=file_ids,json=fileIds,proto3" json:"file_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskRequest) Reset() {
	*x = AskRequest{}
	mi := &file_ai_v1_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskRequest) ProtoMessage() {}

func (x *AskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskRequest.ProtoReflect.Descriptor instead.
func (*AskRequest) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{4}
}

func (x *AskRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *AskRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *AskRequest) GetFolderId() string {
	if x != nil && x.FolderId != nil {
		return *x.FolderId
	}
	return ""
}

func (x *AskRequest) GetFileIds() []string {
	if x != nil {
		return x.FileIds
	}
	return nil
}

type AskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	Citations     []*Citation            `protobuf:"bytes,2,rep,name=citations,proto3" json:"citations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskResponse) Reset() {
	*x = AskResponse{}
	mi := &file_ai_v1_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskResponse) ProtoMessage() {}

func (x *AskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskResponse.ProtoReflect.Descriptor instead.
func (*AskResponse) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{5}
}

func (x *AskResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *AskResponse) GetCitations() []*Citation {
	if x != nil {
		return x.Citations
	}
	return nil
}

type ReprocessRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OwnerId        string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	FileId         string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReprocessRequest) Reset() {
	*x = ReprocessRequest{}
	mi := &file_ai_v1_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReprocessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReprocessRequest) ProtoMessage() {}

func (x *ReprocessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReprocessRequest.ProtoReflect.Descriptor instead.
func (*ReprocessRequest) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{6}
}

func (x *ReprocessRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ReprocessRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *ReprocessRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type ReprocessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReprocessResponse) Reset() {
	*x = ReprocessResponse{}
	mi := &file_ai_v1_ai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReprocessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReprocessResponse) ProtoMessage() {}

func (x *ReprocessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReprocessResponse.ProtoReflect.Descriptor instead.
func (*ReprocessResponse) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{7}
}

func (x *ReprocessResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskType      string                 `protobuf:"bytes,2,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	ResourceType  string                 `protobuf:"bytes,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId    string                 `protobuf:"bytes,4,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Progress      int32                  `protobuf:"varint,6,opt,name=progress,proto3" json:"progress,omitempty"`
	Attempt       int32                  `protobuf:"varint,7,opt,name=attempt,proto3" json:"attempt,omitempty"`
	ErrorCode     *string                `protobuf:"bytes,8,opt,name=error_code,json=errorCode,proto3,oneof" json:"error_code,omitempty"`
	ErrorMessage  *string                `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_ai_v1_ai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{8}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *Task) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *Task) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Task) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *Task) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Task) GetErrorCode() string {
	if x != nil && x.ErrorCode != nil {
		return *x.ErrorCode
	}
	return ""
}

func (x *Task) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Task) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_ai_v1_ai_proto protoreflect.FileDescriptor

const file_ai_v1_ai_proto_rawDesc = "" +
	"\n" +
	"\x0eai/v1/ai.proto\x12\fyunpan.ai.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe8\x01\n" +
	"\rSearchRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12 \n" +
	"\tfolder_id\x18\x04 \x01(\tH\x00R\bfolderId\x88\x01\x01\x12-\n" +
	"\x12include_subfolders\x18\x05 \x01(\bR\x11includeSubfolders\x12\x1d\n" +
	"\n" +
	"mime_types\x18\x06 \x03(\tR\tmimeTypes\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limitB\f\n" +
	"\n" +
	"_folder_id\"\xce\x02\n" +
	"\aFileRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x1b\n" +
	"\tfolder_id\x18\x03 \x01(\tR\bfolderId\x12\x1b\n" +
	"\tobject_id\x18\x04 \x01(\tR\bobjectId\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x06 \x01(\x03R\tsizeBytes\x12\x1b\n" +
	"\tmime_type\x18\a \x01(\tR\bmimeType\x12\x18\n" +
	"\aversion\x18\b \x01(\x03R\aversion\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xcb\x01\n" +
	"\bCitation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12$\n" +
	"\vpage_number\x18\x04 \x01(\x05H\x00R\n" +
	"pageNumber\x88\x01\x01\x12\x1d\n" +
	"\asection\x18\x05 \x01(\tH\x01R\asection\x88\x01\x01\x12\x18\n" +
	"\aexcerpt\x18\x06 \x01(\tR\aexcerptB\x0e\n" +
	"\f_page_numberB\n" +
	"\n" +
	"\b_section\"\xa1\x01\n" +
	"\tSearchHit\x12)\n" +
	"\x04file\x18\x01 \x01(\v2\x15.yunpan.ai.v1.FileRefR\x04file\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x1d\n" +
	"\n" +
	"match_type\x18\x03 \x01(\tR\tmatchType\x124\n" +
	"\tcitations\x18\x04 \x03(\v2\x16.yunpan.ai.v1.CitationR\tcitations\"\x8e\x01\n" +
	"\n" +
	"AskRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\x12 \n" +
	"\tfolder_id\x18\x03 \x01(\tH\x00R\bfolderId\x88\x01\x01\x12\x19\n" +
	"\bfile_ids\x18\x04 \x03(\tR\afileIdsB\f\n" +
	"\n" +
	"_folder_id\"[\n" +
	"\vAskResponse\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\x124\n" +
	"\tcitations\x18\x02 \x03(\v2\x16.yunpan.ai.v1.CitationR\tcitations\"o\n" +
	"\x10ReprocessRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\";\n" +
	"\x11ReprocessResponse\x12&\n" +
	"\x04task\x18\x01 \x01(\v2\x12.yunpan.ai.v1.TaskR\x04task\"\xac\x03\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttask_type\x18\x02 \x01(\tR\btaskType\x12#\n" +
	"\rresource_type\x18\x03 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x04 \x01(\tR\n" +
	"resourceId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1a\n" +
	"\bprogress\x18\x06 \x01(\x05R\bprogress\x12\x18\n" +
	"\aattempt\x18\a \x01(\x05R\aattempt\x12\"\n" +
	"\n" +
	"error_code\x18\b \x01(\tH\x00R\terrorCode\x88\x01\x01\x12(\n" +
	"\rerror_message\x18\t \x01(\tH\x01R\ferrorMessage\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\r\n" +
	"\v_error_codeB\x10\n" +
	"\x0e_error_message2\xd7\x01\n" +
	"\tAIService\x12@\n" +
	"\x06Search\x12\x1b.yunpan.ai.v1.SearchRequest\x1a\x17.yunpan.ai.v1.SearchHit0\x01\x12:\n" +
	"\x03Ask\x12\x18.yunpan.ai.v1.AskRequest\x1a\x19.yunpan.ai.v1.AskResponse\x12L\n" +
	"\tReprocess\x12\x1e.yunpan.ai.v1.ReprocessRequest\x1a\x1f.yunpan.ai.v1.ReprocessResponseB:Z8github.com/11bronx11/bx_yunpan/backend/internal/ai/pb;pbb\x06proto3"

var (
	file_ai_v1_ai_proto_rawDescOnce sync.Once
	file_ai_v1_ai_proto_rawDescData []byte
)

func file_ai_v1_ai_proto_rawDescGZIP() []byte {
	file_ai_v1_ai_proto_rawDescOnce.Do(func() {
		file_ai_v1_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_v1_ai_proto_rawDesc), len(file_ai_v1_ai_proto_rawDesc)))
	})
	return file_ai_v1_ai_proto_rawDescData
}

var file_ai_v1_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_ai_v1_ai_proto_goTypes = []any{
	(*SearchRequest)(nil),         // 0: yunpan.ai.v1.SearchRequest
	(*FileRef)(nil),               // 1: yunpan.ai.v1.FileRef
	(*Citation)(nil),              // 2: yunpan.ai.v1.Citation
	(*SearchHit)(nil),             // 3: yunpan.ai.v1.SearchHit
	(*AskRequest)(nil),            // 4: yunpan.ai.v1.AskRequest
	(*AskResponse)(nil),           // 5: yunpan.ai.v1.AskResponse
	(*ReprocessRequest)(nil),      // 6: yunpan.ai.v1.ReprocessRequest
	(*ReprocessResponse)(nil),     // 7: yunpan.ai.v1.ReprocessResponse
	(*Task)(nil),                  // 8: yunpan.ai.v1.Task
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_ai_v1_ai_proto_depIdxs = []int32{
	9,  // 0: yunpan.ai.v1.FileRef.created_at:type_name -> google.protobuf.Timestamp
	9,  // 1: yunpan.ai.v1.FileRef.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 2: yunpan.ai.v1.SearchHit.file:type_name -> yunpan.ai.v1.FileRef
	2,  // 3: yunpan.ai.v1.SearchHit.citations:type_name -> yunpan.ai.v1.Citation
	2,  // 4: yunpan.ai.v1.AskResponse.citations:type_name -> yunpan.ai.v1.Citation
	8,  // 5: yunpan.ai.v1.ReprocessResponse.task:type_name -> yunpan.ai.v1.Task
	9,  // 6: yunpan.ai.v1.Task.created_at:type_name -> google.protobuf.Timestamp
	9,  // 7: yunpan.ai.v1.Task.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 8: yunpan.ai.v1.AIService.Search:input_type -> yunpan.ai.v1.SearchRequest
	4,  // 9: yunpan.ai.v1.AIService.Ask:input_type -> yunpan.ai.v1.AskRequest
	6,  // 10: yunpan.ai.v1.AIService.Reprocess:input_type -> yunpan.ai.v1.ReprocessRequest
	3,  // 11: yunpan.ai.v1.AIService.Search:output_type -> yunpan.ai.v1.SearchHit
	5,  // 12: yunpan.ai.v1.AIService.Ask:output_type -> yunpan.ai.v1.AskResponse
	7,  // 13: yunpan.ai.v1.AIService.Reprocess:output_type -> yunpan.ai.v1.ReprocessResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_ai_v1_ai_proto_init() }
func file_ai_v1_ai_proto_init() {
	if File_ai_v1_ai_proto != nil {
		return
	}
	file_ai_v1_ai_proto_msgTypes[0].OneofWrappers = []any{}
	file_ai_v1_ai_proto_msgTypes[2].OneofWrappers = []any{}
	file_ai_v1_ai_proto_msgTypes[4].OneofWrappers = []any{}
	file_ai_v1_ai_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_v1_ai_proto_rawDesc), len(file_ai_v1_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_v1_ai_proto_goTypes,
		DependencyIndexes: file_ai_v1_ai_proto_depIdxs,
		MessageInfos:      file_ai_v1_ai_proto_msgTypes,
	}.Build()
	File_ai_v1_ai_proto = out.File
	file_ai_v1_ai_proto_goTypes = nil
	file_ai_v1_ai_proto_depIdxs = nil
}
