// Package contract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package contract

import (
	"encoding/json"
	"errors"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AIDocumentStatus.
const (
	AIDocumentStatusFailed      AIDocumentStatus = "failed"
	AIDocumentStatusIndexed     AIDocumentStatus = "indexed"
	AIDocumentStatusPending     AIDocumentStatus = "pending"
	AIDocumentStatusProcessing  AIDocumentStatus = "processing"
	AIDocumentStatusUnsupported AIDocumentStatus = "unsupported"
)

// Valid indicates whether the value is a known member of the AIDocumentStatus enum.
func (e AIDocumentStatus) Valid() bool {
	switch e {
	case AIDocumentStatusFailed:
		return true
	case AIDocumentStatusIndexed:
		return true
	case AIDocumentStatusPending:
		return true
	case AIDocumentStatusProcessing:
		return true
	case AIDocumentStatusUnsupported:
		return true
	default:
		return false
	}
}

// Defines values for AuthResponseTokenType.
const (
	Bearer AuthResponseTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the AuthResponseTokenType enum.
func (e AuthResponseTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for FileEntryAiStatus.
const (
	FileEntryAiStatusFailed      FileEntryAiStatus = "failed"
	FileEntryAiStatusIndexed     FileEntryAiStatus = "indexed"
	FileEntryAiStatusPending     FileEntryAiStatus = "pending"
	FileEntryAiStatusProcessing  FileEntryAiStatus = "processing"
	FileEntryAiStatusUnsupported FileEntryAiStatus = "unsupported"
)

// Valid indicates whether the value is a known member of the FileEntryAiStatus enum.
func (e FileEntryAiStatus) Valid() bool {
	switch e {
	case FileEntryAiStatusFailed:
		return true
	case FileEntryAiStatusIndexed:
		return true
	case FileEntryAiStatusPending:
		return true
	case FileEntryAiStatusProcessing:
		return true
	case FileEntryAiStatusUnsupported:
		return true
	default:
		return false
	}
}

// Defines values for FileEntryType.
const (
	File FileEntryType = "file"
)

// Valid indicates whether the value is a known member of the FileEntryType enum.
func (e FileEntryType) Valid() bool {
	switch e {
	case File:
		return true
	default:
		return false
	}
}

// Defines values for FolderType.
const (
	FolderTypeFolder FolderType = "folder"
)

// Valid indicates whether the value is a known member of the FolderType enum.
func (e FolderType) Valid() bool {
	switch e {
	case FolderTypeFolder:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Degraded    HealthStatus = "degraded"
	Ok          HealthStatus = "ok"
	Unavailable HealthStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Ok:
		return true
	case Unavailable:
		return true
	default:
		return false
	}
}

// Defines values for InstantUploadResponseMode.
const (
	Instant InstantUploadResponseMode = "instant"
)

// Valid indicates whether the value is a known member of the InstantUploadResponseMode enum.
func (e InstantUploadResponseMode) Valid() bool {
	switch e {
	case Instant:
		return true
	default:
		return false
	}
}

// Defines values for MultipartUploadResponseMode.
const (
	Multipart MultipartUploadResponseMode = "multipart"
)

// Valid indicates whether the value is a known member of the MultipartUploadResponseMode enum.
func (e MultipartUploadResponseMode) Valid() bool {
	switch e {
	case Multipart:
		return true
	default:
		return false
	}
}

// Defines values for PreviewKind.
const (
	PreviewKindImage       PreviewKind = "image"
	PreviewKindPdf         PreviewKind = "pdf"
	PreviewKindProcessing  PreviewKind = "processing"
	PreviewKindText        PreviewKind = "text"
	PreviewKindUnsupported PreviewKind = "unsupported"
)

// Valid indicates whether the value is a known member of the PreviewKind enum.
func (e PreviewKind) Valid() bool {
	switch e {
	case PreviewKindImage:
		return true
	case PreviewKindPdf:
		return true
	case PreviewKindProcessing:
		return true
	case PreviewKindText:
		return true
	case PreviewKindUnsupported:
		return true
	default:
		return false
	}
}

// Defines values for SearchHitMatchType.
const (
	SearchHitMatchTypeFulltext SearchHitMatchType = "fulltext"
	SearchHitMatchTypeHybrid   SearchHitMatchType = "hybrid"
	SearchHitMatchTypeName     SearchHitMatchType = "name"
	SearchHitMatchTypeSemantic SearchHitMatchType = "semantic"
)

// Valid indicates whether the value is a known member of the SearchHitMatchType enum.
func (e SearchHitMatchType) Valid() bool {
	switch e {
	case SearchHitMatchTypeFulltext:
		return true
	case SearchHitMatchTypeHybrid:
		return true
	case SearchHitMatchTypeName:
		return true
	case SearchHitMatchTypeSemantic:
		return true
	default:
		return false
	}
}

// Defines values for SearchRequestMode.
const (
	SearchRequestModeFulltext SearchRequestMode = "fulltext"
	SearchRequestModeHybrid   SearchRequestMode = "hybrid"
	SearchRequestModeName     SearchRequestMode = "name"
	SearchRequestModeSemantic SearchRequestMode = "semantic"
)

// Valid indicates whether the value is a known member of the SearchRequestMode enum.
func (e SearchRequestMode) Valid() bool {
	switch e {
	case SearchRequestModeFulltext:
		return true
	case SearchRequestModeHybrid:
		return true
	case SearchRequestModeName:
		return true
	case SearchRequestModeSemantic:
		return true
	default:
		return false
	}
}

// Defines values for TaskStatus.
const (
	TaskStatusCanceled  TaskStatus = "canceled"
	TaskStatusFailed    TaskStatus = "failed"
	TaskStatusPending   TaskStatus = "pending"
	TaskStatusRunning   TaskStatus = "running"
	TaskStatusSucceeded TaskStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the TaskStatus enum.
func (e TaskStatus) Valid() bool {
	switch e {
	case TaskStatusCanceled:
		return true
	case TaskStatusFailed:
		return true
	case TaskStatusPending:
		return true
	case TaskStatusRunning:
		return true
	case TaskStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for UploadSessionStatus.
const (
	UploadSessionStatusAborted   UploadSessionStatus = "aborted"
	UploadSessionStatusCompleted UploadSessionStatus = "completed"
	UploadSessionStatusCreated   UploadSessionStatus = "created"
	UploadSessionStatusExpired   UploadSessionStatus = "expired"
	UploadSessionStatusFailed    UploadSessionStatus = "failed"
	UploadSessionStatusUploading UploadSessionStatus = "uploading"
	UploadSessionStatusVerifying UploadSessionStatus = "verifying"
)

// Valid indicates whether the value is a known member of the UploadSessionStatus enum.
func (e UploadSessionStatus) Valid() bool {
	switch e {
	case UploadSessionStatusAborted:
		return true
	case UploadSessionStatusCompleted:
		return true
	case UploadSessionStatusCreated:
		return true
	case UploadSessionStatusExpired:
		return true
	case UploadSessionStatusFailed:
		return true
	case UploadSessionStatusUploading:
		return true
	case UploadSessionStatusVerifying:
		return true
	default:
		return false
	}
}

// Defines values for UserStatus.
const (
	UserStatusActive   UserStatus = "active"
	UserStatusDisabled UserStatus = "disabled"
)

// Valid indicates whether the value is a known member of the UserStatus enum.
func (e UserStatus) Valid() bool {
	switch e {
	case UserStatusActive:
		return true
	case UserStatusDisabled:
		return true
	default:
		return false
	}
}

// Defines values for Sort.
const (
	SortNameAsc     Sort = "name_asc"
	SortNameDesc    Sort = "name_desc"
	SortSizeDesc    Sort = "size_desc"
	SortUpdatedDesc Sort = "updated_desc"
)

// Valid indicates whether the value is a known member of the Sort enum.
func (e Sort) Valid() bool {
	switch e {
	case SortNameAsc:
		return true
	case SortNameDesc:
		return true
	case SortSizeDesc:
		return true
	case SortUpdatedDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListFolderChildrenParamsSort.
const (
	ListFolderChildrenParamsSortNameAsc     ListFolderChildrenParamsSort = "name_asc"
	ListFolderChildrenParamsSortNameDesc    ListFolderChildrenParamsSort = "name_desc"
	ListFolderChildrenParamsSortSizeDesc    ListFolderChildrenParamsSort = "size_desc"
	ListFolderChildrenParamsSortUpdatedDesc ListFolderChildrenParamsSort = "updated_desc"
)

// Valid indicates whether the value is a known member of the ListFolderChildrenParamsSort enum.
func (e ListFolderChildrenParamsSort) Valid() bool {
	switch e {
	case ListFolderChildrenParamsSortNameAsc:
		return true
	case ListFolderChildrenParamsSortNameDesc:
		return true
	case ListFolderChildrenParamsSortSizeDesc:
		return true
	case ListFolderChildrenParamsSortUpdatedDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListActiveUploadsParamsStatus.
const (
	ListActiveUploadsParamsStatusActive ListActiveUploadsParamsStatus = "active"
)

// Valid indicates whether the value is a known member of the ListActiveUploadsParamsStatus enum.
func (e ListActiveUploadsParamsStatus) Valid() bool {
	switch e {
	case ListActiveUploadsParamsStatusActive:
		return true
	default:
		return false
	}
}

// AIDocument defines model for AIDocument.
type AIDocument struct {
	ErrorCode *string `json:"error_code,omitempty"`

	// FileId Example: 0198a1f0-7b2a-7000-8000-000000000001
	FileId          UUID             `json:"file_id"`
	Language        *string          `json:"language,omitempty"`
	ModelVersion    string           `json:"model_version"`
	PipelineVersion string           `json:"pipeline_version"`
	Status          AIDocumentStatus `json:"status"`
	Summary         *string          `json:"summary,omitempty"`
	Tags            *[]string        `json:"tags,omitempty"`
}

// AIDocumentStatus defines model for AIDocument.Status.
type AIDocumentStatus string

// AskRequest defines model for AskRequest.
type AskRequest struct {
	FileIds  *[]UUID       `json:"file_ids,omitempty"`
	FolderId *NullableUUID `json:"folder_id,omitempty"`
	Question string        `json:"question"`
}

// AskResponse defines model for AskResponse.
type AskResponse struct {
	Answer    string     `json:"answer"`
	Citations []Citation `json:"citations"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	AccessToken *string                `json:"access_token,omitempty"`
	ExpiresIn   int                    `json:"expires_in"`
	TokenType   *AuthResponseTokenType `json:"token_type,omitempty"`
	User        User                   `json:"user"`
}

// AuthResponseTokenType defines model for AuthResponse.TokenType.
type AuthResponseTokenType string

// Breadcrumb defines model for Breadcrumb.
type Breadcrumb struct {
	Items []Folder `json:"items"`
}

// Citation defines model for Citation.
type Citation struct {
	Excerpt string `json:"excerpt"`

	// FileId Example: 0198a1f0-7b2a-7000-8000-000000000001
	FileId     UUID    `json:"file_id"`
	FileName   string  `json:"file_name"`
	Id         string  `json:"id"`
	PageNumber *int    `json:"page_number,omitempty"`
	Section    *string `json:"section,omitempty"`
}

// ConfirmPartsRequest defines model for ConfirmPartsRequest.
type ConfirmPartsRequest struct {
	Parts []ConfirmedPart `json:"parts"`
}

// ConfirmedPart defines model for ConfirmedPart.
type ConfirmedPart struct {
	Checksum   *string `json:"checksum,omitempty"`
	Etag       string  `json:"etag"`
	PartNumber int     `json:"part_number"`
	SizeBytes  int64   `json:"size_bytes"`
}

// ConfirmedUploadPart defines model for ConfirmedUploadPart.
type ConfirmedUploadPart struct {
	CompletedAt Timestamp `json:"completed_at"`
	PartNumber  int       `json:"part_number"`
	SizeBytes   int64     `json:"size_bytes"`
}

// CreateFolderRequest defines model for CreateFolderRequest.
type CreateFolderRequest struct {
	Name string `json:"name"`

	// ParentId Example: 0198a1f0-7b2a-7000-8000-000000000001
	ParentId UUID `json:"parent_id"`
}

// CreateShareRequest defines model for CreateShareRequest.
type CreateShareRequest struct {
	ExpiresAt *Timestamp `json:"expires_at,omitempty"`

	// FileId Example: 0198a1f0-7b2a-7000-8000-000000000001
	FileId UUID `json:"file_id"`
}

// CreateShareResponse defines model for CreateShareResponse.
type CreateShareResponse struct {
	Share    Share   `json:"share"`
	ShareKey *string `json:"share_key,omitempty"`
}

// CreateUploadRequest defines model for CreateUploadRequest.
type CreateUploadRequest struct {
	Filename string `json:"filename"`

	// FolderId Example: 0198a1f0-7b2a-7000-8000-000000000001
	FolderId  UUID   `json:"folder_id"`
	MimeType  string `json:"mime_type"`
	Sha256    string `json:"sha256"`
	SizeBytes int64  `json:"size_bytes"`
}

// CreateUploadResponse defines model for CreateUploadResponse.
type CreateUploadResponse struct {
	union json.RawMessage
}

// DriveItem defines model for DriveItem.
type DriveItem struct {
	union json.RawMessage
}

// DriveItemPage defines model for DriveItemPage.
type DriveItemPage struct {
	Items []DriveItem `json:"items"`
	Page  PageInfo    `json:"page"`
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Error struct {
		// Code Example: upload.hash_mismatch
		Code    string                  `json:"code"`
		Details *map[string]interface{} `json:"details,omitempty"`
		Message string                  `json:"message"`
	} `json:"error"`
	RequestId string `json:"request_id"`
}

// FileEntry defines model for FileEntry.
type FileEntry struct {
	AiStatus  *FileEntryAiStatus `json:"ai_status,omitempty"`
	CreatedAt Timestamp          `json:"created_at"`

	// FolderId Example: 0198a1f0-7b2a-7000-8000-000000000001
	FolderId UUID `json:"folder_id"`

	// Id Example: 0198a1f0-7b2a-7000-8000-000000000001
	Id       UUID   `json:"id"`
	MimeType string `json:"mime_type"`
	Name     string `json:"name"`

	// ObjectId Example: 0198a1f0-7b2a-7000-8000-000000000001
	ObjectId UUID `json:"object_id"`

	// OwnerId Example: 0198a1f0-7b2a-7000-8000-000000000001
	OwnerId      UUID          `json:"owner_id"`
	SizeBytes    int64         `json:"size_bytes"`
	ThumbnailUrl *string       `json:"thumbnail_url,omitempty"`
	Type         FileEntryType `json:"type"`
	UpdatedAt    Timestamp     `json:"updated_at"`
	Version      int64         `json:"version"`
}

// FileEntryAiStatus defines model for FileEntry.AiStatus.
type FileEntryAiStatus string

// FileEntryType defines model for FileEntry.Type.
type FileEntryType string

// Folder defines model for Folder.
type Folder struct {
	CreatedAt Timestamp `json:"created_at"`

	// Id Example: 0198a1f0-7b2a-7000-8000-000000000001
	Id   UUID   `json:"id"`
	Name string `json:"name"`

	// OwnerId Example: 0198a1f0-7b2a-7000-8000-000000000001
	OwnerId   UUID          `json:"owner_id"`
	ParentId  *NullableUUID `json:"parent_id,omitempty"`
	Type      FolderType    `json:"type"`
	UpdatedAt Timestamp     `json:"updated_at"`
	Version   int64         `json:"version"`
}

// FolderType defines model for Folder.Type.
type FolderType string

// Health defines model for Health.
type Health struct {
	Checks *map[string]string `json:"checks,omitempty"`
	Status HealthStatus       `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// ImportShareRequest defines model for ImportShareRequest.
type ImportShareRequest struct {
	// TargetFolderId Example: 0198a1f0-7b2a-7000-8000-000000000001
	TargetFolderId UUID `json:"target_folder_id"`
}

// ImportShareResponse defines model for ImportShareResponse.
type ImportShareResponse struct {
	ImportedFile FileEntry `json:"imported_file"`

	// ShareId Example: 0198a1f0-7b2a-7000-8000-000000000001
	ShareId UUID `json:"share_id"`
}

// InstantUploadResponse defines model for InstantUploadResponse.
type InstantUploadResponse struct {
	File FileEntry                 `json:"file"`
	Mode InstantUploadResponseMode `json:"mode"`
}

// InstantUploadResponseMode defines model for InstantUploadResponse.Mode.
type InstantUploadResponseMode string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// MoveRequest defines model for MoveRequest.
type MoveRequest struct {
	// TargetFolderId Example: 0198a1f0-7b2a-7000-8000-000000000001
	TargetFolderId UUID `json:"target_folder_id"`
}

// MultipartUploadResponse defines model for MultipartUploadResponse.
type MultipartUploadResponse struct {
	Mode   MultipartUploadResponseMode `json:"mode"`
	Upload UploadSession               `json:"upload"`
}

// MultipartUploadResponseMode defines model for MultipartUploadResponse.Mode.
type MultipartUploadResponseMode string

// NullableTimestamp defines model for NullableTimestamp.
type NullableTimestamp = time.Time

// NullableUUID defines model for NullableUUID.
type NullableUUID = openapi_types.UUID

// PageInfo defines model for PageInfo.
type PageInfo struct {
	HasMore    bool    `json:"has_more"`
	NextCursor *string `json:"next_cursor,omitempty"`
}

// PresignPartsRequest defines model for PresignPartsRequest.
type PresignPartsRequest struct {
	PartNumbers []int `json:"part_numbers"`
}

// PresignPartsResponse defines model for PresignPartsResponse.
type PresignPartsResponse struct {
	Parts []PresignedPart `json:"parts"`
}

// PresignedPart defines model for PresignedPart.
type PresignedPart struct {
	ExpiresAt  Timestamp `json:"expires_at"`
	PartNumber int       `json:"part_number"`
	Url        string    `json:"url"`
}

// PresignedUrl defines model for PresignedUrl.
type PresignedUrl struct {
	ExpiresAt Timestamp `json:"expires_at"`
	Url       string    `json:"url"`
}

// Preview defines model for Preview.
type Preview struct {
	ExpiresAt *NullableTimestamp `json:"expires_at,omitempty"`
	Height    *int               `json:"height,omitempty"`
	Kind      PreviewKind        `json:"kind"`
	Url       *string            `json:"url,omitempty"`
	Width     *int               `json:"width,omitempty"`
}

// PreviewKind defines model for Preview.Kind.
type PreviewKind string

// PublicShare defines model for PublicShare.
type PublicShare struct {
	ExpiresAt *NullableTimestamp `json:"expires_at"`
	FileName  string             `json:"file_name"`

	// Id Example: 0198a1f0-7b2a-7000-8000-000000000001
	Id               UUID   `json:"id"`
	MimeType         string `json:"mime_type"`
	OwnerDisplayName string `json:"owner_display_name"`
	SizeBytes        int64  `json:"size_bytes"`
}

// PublicShareContent defines model for PublicShareContent.
type PublicShareContent struct {
	Preview Preview     `json:"preview"`
	Share   PublicShare `json:"share"`
}

// Quota defines model for Quota.
type Quota struct {
	QuotaBytes       int64 `json:"quota_bytes"`
	ReservedBytes    int64 `json:"reserved_bytes"`
	UsedLogicalBytes int64 `json:"used_logical_bytes"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    *openapi_types.Email `json:"email,omitempty"`
	Password string               `json:"password"`
	Username string               `json:"username"`
}

// RenameRequest defines model for RenameRequest.
type RenameRequest struct {
	Name string `json:"name"`
}

// ResolveShareRequest defines model for ResolveShareRequest.
type ResolveShareRequest struct {
	ShareKey string `json:"share_key"`
}

// ResolveShareResponse defines model for ResolveShareResponse.
type ResolveShareResponse struct {
	ExpiresIn        int         `json:"expires_in"`
	Share            PublicShare `json:"share"`
	ShareAccessToken *string     `json:"share_access_token,omitempty"`
}

// SearchHit defines model for SearchHit.
type SearchHit struct {
	Citations []Citation         `json:"citations"`
	File      FileEntry          `json:"file"`
	MatchType SearchHitMatchType `json:"match_type"`
	Score     float64            `json:"score"`
}

// SearchHitMatchType defines model for SearchHit.MatchType.
type SearchHitMatchType string

// SearchRequest defines model for SearchRequest.
type SearchRequest struct {
	FolderId          *NullableUUID     `json:"folder_id,omitempty"`
	IncludeSubfolders *bool             `json:"include_subfolders,omitempty"`
	Limit             *int              `json:"limit,omitempty"`
	MimeTypes         *[]string         `json:"mime_types,omitempty"`
	Mode              SearchRequestMode `json:"mode"`
	Query             string            `json:"query"`
}

// SearchRequestMode defines model for SearchRequest.Mode.
type SearchRequestMode string

// SearchResponse defines model for SearchResponse.
type SearchResponse struct {
	Hits []SearchHit `json:"hits"`
	Page PageInfo    `json:"page"`
}

// Share defines model for Share.
type Share struct {
	CreatedAt Timestamp          `json:"created_at"`
	ExpiresAt *NullableTimestamp `json:"expires_at,omitempty"`

	// FileId Example: 0198a1f0-7b2a-7000-8000-000000000001
	FileId UUID `json:"file_id"`

	// Id Example: 0198a1f0-7b2a-7000-8000-000000000001
	Id        UUID               `json:"id"`
	RevokedAt *NullableTimestamp `json:"revoked_at,omitempty"`
}

// SharePage defines model for SharePage.
type SharePage struct {
	Items []Share  `json:"items"`
	Page  PageInfo `json:"page"`
}

// Task defines model for Task.
type Task struct {
	Attempt      int       `json:"attempt"`
	CreatedAt    Timestamp `json:"created_at"`
	ErrorCode    *string   `json:"error_code,omitempty"`
	ErrorMessage *string   `json:"error_message,omitempty"`

	// Id Example: 0198a1f0-7b2a-7000-8000-000000000001
	Id           UUID          `json:"id"`
	Progress     int           `json:"progress"`
	ResourceId   *NullableUUID `json:"resource_id,omitempty"`
	ResourceType *string       `json:"resource_type,omitempty"`
	Status       TaskStatus    `json:"status"`
	TaskType     string        `json:"task_type"`
	UpdatedAt    Timestamp     `json:"updated_at"`
}

// TaskStatus defines model for Task.Status.
type TaskStatus string

// Timestamp defines model for Timestamp.
type Timestamp = time.Time

// UUID Example: 0198a1f0-7b2a-7000-8000-000000000001
type UUID = openapi_types.UUID

// UploadSession defines model for UploadSession.
type UploadSession struct {
	CompletedEntryId  *NullableUUID         `json:"completed_entry_id,omitempty"`
	CompletedObjectId *NullableUUID         `json:"completed_object_id,omitempty"`
	ConfirmedParts    []ConfirmedUploadPart `json:"confirmed_parts"`
	CreatedAt         Timestamp             `json:"created_at"`
	ErrorCode         *string               `json:"error_code,omitempty"`
	ExpiresAt         Timestamp             `json:"expires_at"`
	Filename          string                `json:"filename"`

	// FolderId Example: 0198a1f0-7b2a-7000-8000-000000000001
	FolderId UUID `json:"folder_id"`

	// Id Example: 0198a1f0-7b2a-7000-8000-000000000001
	Id        UUID                `json:"id"`
	PartCount int                 `json:"part_count"`
	PartSize  int64               `json:"part_size"`
	Sha256    string              `json:"sha256"`
	SizeBytes int64               `json:"size_bytes"`
	Status    UploadSessionStatus `json:"status"`
}

// UploadSessionStatus defines model for UploadSession.Status.
type UploadSessionStatus string

// UploadSessionList defines model for UploadSessionList.
type UploadSessionList struct {
	Items []UploadSession `json:"items"`
}

// User defines model for User.
type User struct {
	CreatedAt Timestamp            `json:"created_at"`
	Email     *openapi_types.Email `json:"email,omitempty"`

	// Id Example: 0198a1f0-7b2a-7000-8000-000000000001
	Id       UUID       `json:"id"`
	Status   UserStatus `json:"status"`
	Username string     `json:"username"`
}

// UserStatus defines model for User.Status.
type UserStatus string

// Cursor defines model for Cursor.
type Cursor = string

// FileId Example: 0198a1f0-7b2a-7000-8000-000000000001
type FileId = UUID

// FolderId Example: 0198a1f0-7b2a-7000-8000-000000000001
type FolderId = UUID

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = openapi_types.UUID

// IfMatch defines model for IfMatch.
type IfMatch = string

// Limit defines model for Limit.
type Limit = int

// Origin defines model for Origin.
type Origin = string

// ShareId Example: 0198a1f0-7b2a-7000-8000-000000000001
type ShareId = UUID

// Sort defines model for Sort.
type Sort string

// TaskId Example: 0198a1f0-7b2a-7000-8000-000000000001
type TaskId = UUID

// UploadId Example: 0198a1f0-7b2a-7000-8000-000000000001
type UploadId = UUID

// Conflict defines model for Conflict.
type Conflict = ErrorEnvelope

// Forbidden defines model for Forbidden.
type Forbidden = ErrorEnvelope

// NotFound defines model for NotFound.
type NotFound = ErrorEnvelope

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = ErrorEnvelope

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = ErrorEnvelope

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorEnvelope

// ValidationError defines model for ValidationError.
type ValidationError = ErrorEnvelope

// LogoutParams defines parameters for Logout.
type LogoutParams struct {
	Origin Origin `json:"Origin"`
}

// RefreshSessionParams defines parameters for RefreshSession.
type RefreshSessionParams struct {
	Origin Origin `json:"Origin"`
}

// DeleteFileParams defines parameters for DeleteFile.
type DeleteFileParams struct {
	// IfMatch Current numeric resource version
	IfMatch IfMatch `json:"If-Match"`
}

// UpdateFileParams defines parameters for UpdateFile.
type UpdateFileParams struct {
	// IfMatch Current numeric resource version
	IfMatch IfMatch `json:"If-Match"`
}

// ReprocessFileAIParams defines parameters for ReprocessFileAI.
type ReprocessFileAIParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// MoveFileParams defines parameters for MoveFile.
type MoveFileParams struct {
	// IfMatch Current numeric resource version
	IfMatch IfMatch `json:"If-Match"`
}

// DeleteFolderParams defines parameters for DeleteFolder.
type DeleteFolderParams struct {
	// IfMatch Current numeric resource version
	IfMatch IfMatch `json:"If-Match"`
}

// UpdateFolderParams defines parameters for UpdateFolder.
type UpdateFolderParams struct {
	// IfMatch Current numeric resource version
	IfMatch IfMatch `json:"If-Match"`
}

// ListFolderChildrenParams defines parameters for ListFolderChildren.
type ListFolderChildrenParams struct {
	Cursor *Cursor                       `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit                        `form:"limit,omitempty" json:"limit,omitempty"`
	Sort   *ListFolderChildrenParamsSort `form:"sort,omitempty" json:"sort,omitempty"`
}

// ListFolderChildrenParamsSort defines parameters for ListFolderChildren.
type ListFolderChildrenParamsSort string

// MoveFolderParams defines parameters for MoveFolder.
type MoveFolderParams struct {
	// IfMatch Current numeric resource version
	IfMatch IfMatch `json:"If-Match"`
}

// ListSharesParams defines parameters for ListShares.
type ListSharesParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ImportShareParams defines parameters for ImportShare.
type ImportShareParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListActiveUploadsParams defines parameters for ListActiveUploads.
type ListActiveUploadsParams struct {
	Status *ListActiveUploadsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// ListActiveUploadsParamsStatus defines parameters for ListActiveUploads.
type ListActiveUploadsParamsStatus string

// CreateUploadParams defines parameters for CreateUpload.
type CreateUploadParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CompleteUploadParams defines parameters for CompleteUpload.
type CompleteUploadParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// AskFilesJSONRequestBody defines body for AskFiles for application/json ContentType.
type AskFilesJSONRequestBody = AskRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = RegisterRequest

// UpdateFileJSONRequestBody defines body for UpdateFile for application/json ContentType.
type UpdateFileJSONRequestBody = RenameRequest

// MoveFileJSONRequestBody defines body for MoveFile for application/json ContentType.
type MoveFileJSONRequestBody = MoveRequest

// CreateFolderJSONRequestBody defines body for CreateFolder for application/json ContentType.
type CreateFolderJSONRequestBody = CreateFolderRequest

// UpdateFolderJSONRequestBody defines body for UpdateFolder for application/json ContentType.
type UpdateFolderJSONRequestBody = RenameRequest

// MoveFolderJSONRequestBody defines body for MoveFolder for application/json ContentType.
type MoveFolderJSONRequestBody = MoveRequest

// ResolveShareJSONRequestBody defines body for ResolveShare for application/json ContentType.
type ResolveShareJSONRequestBody = ResolveShareRequest

// SearchJSONRequestBody defines body for Search for application/json ContentType.
type SearchJSONRequestBody = SearchRequest

// CreateShareJSONRequestBody defines body for CreateShare for application/json ContentType.
type CreateShareJSONRequestBody = CreateShareRequest

// ImportShareJSONRequestBody defines body for ImportShare for application/json ContentType.
type ImportShareJSONRequestBody = ImportShareRequest

// CreateUploadJSONRequestBody defines body for CreateUpload for application/json ContentType.
type CreateUploadJSONRequestBody = CreateUploadRequest

// ConfirmUploadPartsJSONRequestBody defines body for ConfirmUploadParts for application/json ContentType.
type ConfirmUploadPartsJSONRequestBody = ConfirmPartsRequest

// PresignUploadPartsJSONRequestBody defines body for PresignUploadParts for application/json ContentType.
type PresignUploadPartsJSONRequestBody = PresignPartsRequest

// AsInstantUploadResponse returns the union data inside the CreateUploadResponse as a InstantUploadResponse
func (t CreateUploadResponse) AsInstantUploadResponse() (InstantUploadResponse, error) {
	var body InstantUploadResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInstantUploadResponse overwrites any union data inside the CreateUploadResponse as the provided InstantUploadResponse
func (t *CreateUploadResponse) FromInstantUploadResponse(v InstantUploadResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"mode":"InstantUploadResponse"}`))
	t.union = b
	return err
}

// MergeInstantUploadResponse performs a merge with any union data inside the CreateUploadResponse, using the provided InstantUploadResponse
func (t *CreateUploadResponse) MergeInstantUploadResponse(v InstantUploadResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"mode":"InstantUploadResponse"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMultipartUploadResponse returns the union data inside the CreateUploadResponse as a MultipartUploadResponse
func (t CreateUploadResponse) AsMultipartUploadResponse() (MultipartUploadResponse, error) {
	var body MultipartUploadResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMultipartUploadResponse overwrites any union data inside the CreateUploadResponse as the provided MultipartUploadResponse
func (t *CreateUploadResponse) FromMultipartUploadResponse(v MultipartUploadResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"mode":"MultipartUploadResponse"}`))
	t.union = b
	return err
}

// MergeMultipartUploadResponse performs a merge with any union data inside the CreateUploadResponse, using the provided MultipartUploadResponse
func (t *CreateUploadResponse) MergeMultipartUploadResponse(v MultipartUploadResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"mode":"MultipartUploadResponse"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CreateUploadResponse) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"mode"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t CreateUploadResponse) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "InstantUploadResponse":
		return t.AsInstantUploadResponse()
	case "MultipartUploadResponse":
		return t.AsMultipartUploadResponse()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t CreateUploadResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CreateUploadResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsFolder returns the union data inside the DriveItem as a Folder
func (t DriveItem) AsFolder() (Folder, error) {
	var body Folder
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFolder overwrites any union data inside the DriveItem as the provided Folder
func (t *DriveItem) FromFolder(v Folder) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"Folder"}`))
	t.union = b
	return err
}

// MergeFolder performs a merge with any union data inside the DriveItem, using the provided Folder
func (t *DriveItem) MergeFolder(v Folder) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"Folder"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFileEntry returns the union data inside the DriveItem as a FileEntry
func (t DriveItem) AsFileEntry() (FileEntry, error) {
	var body FileEntry
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFileEntry overwrites any union data inside the DriveItem as the provided FileEntry
func (t *DriveItem) FromFileEntry(v FileEntry) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"FileEntry"}`))
	t.union = b
	return err
}

// MergeFileEntry performs a merge with any union data inside the DriveItem, using the provided FileEntry
func (t *DriveItem) MergeFileEntry(v FileEntry) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"FileEntry"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t DriveItem) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t DriveItem) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "FileEntry":
		return t.AsFileEntry()
	case "Folder":
		return t.AsFolder()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t DriveItem) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *DriveItem) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
